name: Run python program

on:
  push:
    branches:
      - main

jobs:
  ci-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Print welcome message
        run: echo "Welcome to GitHub Actions"